{% set version = "3.4.3" %}

package:
  name: constructor
  version: {{ version }}

source:
  - url: https://github.com/conda/constructor/archive/{{ version }}.tar.gz
    sha256: 4a1f5ae2ba74175cc5d0770d6d43147253091f8869fa20568a02d5ddb7963dee

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  entry_points:
    - constructor = constructor.main:main
  skip: true  # [py<37]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - conda >=4.6,<23.1.0
    - python
    - ruamel_yaml >=0.11.14,<0.16
    - conda-standalone
    - pillow >=3.1     # [win or osx]
    - nsis >=3.08      # [win]
  run_constrained:     # [unix]
    - nsis >=3.08      # [unix]
test:
  source_files:
    - tests
    - scripts
    - examples
  requires:
    - pillow >=3.1
    - pip
    - pytest
  commands:
    - pip check
    - pytest -v tests
    # Long running integration tests
    - python scripts/run_examples.py  # [not win]
    - test_win.bat  # [win]
    - constructor -V
  imports:
    - constructor

about:
  home: https://github.com/conda/constructor
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: create installer from conda packages
  description: |
    Constructor is a tool for constructing an installer for a collection of
    conda packages. It creates an Anaconda-like installer consisting of
    packages.
  doc_url: https://conda.github.io/constructor
  dev_url: https://github.com/conda/constructor

extra:
  recipe-maintainers:
    - jakirkham
    - jschueller
    - mbargull
    - msarahan
