{% set version = "3.12.2" %}

package:
  name: constructor
  version: {{ version }}

source:
  - url: https://github.com/conda/constructor/archive/{{ version }}.tar.gz
    sha256: 224fe4b51080aaefcf5272c708b3ee759d4239eaad162724931fae2123fd7286
    patches:                        # [aarch64]
      - raspberry-pi-warning.patch  # [aarch64]

build:
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
    - NSIS_USING_LOG_BUILD=1   # [win]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - constructor = constructor.main:main
  skip: true  # [py<38]

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools-scm
    - wheel
  run:
    - conda >=4.6
    - python
    - ruamel.yaml >=0.11.14,<0.19
    - conda-standalone
    - pillow >=3.1     # [win or osx]
    - nsis >=3.08      # [win]
    - jinja2
    - jsonschema >=4
  run_constrained:     # [unix]
    - nsis >=3.08      # [unix]
    - conda-libmamba-solver !=24.11.0
    - pydantic >=2
test:
  source_files:
    - tests
    # Include when running examples
    # - scripts
    # - examples
  requires:
    - pip
    - pytest
    - conda-libmamba-solver
    - nsis =*=*log*  # [win]
    - pywin32        # [win]
  commands:
    - pip check
    - pytest -v tests -k "not examples"
    # Long running integration tests
    # - python scripts/run_examples.py  # [not win]
    - constructor --help
    - constructor -V
  imports:
    - constructor

about:
  home: https://docs.conda.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: create installer from conda packages
  description: |
    Constructor is a tool for constructing an installer for a collection of
    conda packages. It creates an Anaconda-like installer consisting of
    packages.
  doc_url: https://docs.conda.io/projects/conda
  dev_url: https://github.com/conda/constructor

extra:
  recipe-maintainers:
    - jakirkham
    - jschueller
    - mbargull
    - msarahan
    - jaimergp
    - marcoesters
