{% set version = "1.3.3" %}
{%set sha256 = "103623bb1148b175659e81ebaf9f3642349a2fcd456dcf6e573f85b2b6ff2177" %}

package:
  name: constructor
  version: {{ version }}

source:
  fn: constructor-{{ version }}.tar.gz
  url: https://github.com/conda/constructor/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python

  run:
    - python
    - libconda
    - pillow >=3.1  # [win]
    - nsis          # [win]

test:
  imports:
    - constructor

  commands:
    - constructor --help

about:
  home: http://github.com/conda/constructor
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: create installer from conda packages

extra:
  recipe-maintainers:
    - jakirkham
