{% set version = "3.3.1" %}

package:
  name: constructor
  version: {{ version }}

source:
  - url: https://github.com/conda/constructor/archive/{{ version }}.tar.gz
    sha256: b9fe6afb60b90f99708e46c871db33c236eb0a1d42652006e8801654820fea3c

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - constructor = constructor.main:main
  patches:
    - 0001-make-directory-arg-optional.patch

requirements:
  build:
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - conda >=4.6
    - python
    - pip
    - setuptools
    - wheel
    - ruamel_yaml >=0.11.14,<0.16
    - conda-standalone
    - chardet
    - pillow >=3.1  # [win]
    - nsis >=3.01  # [win]
test:
  source_files:
    - tests
    - scripts
    - examples
  requires:
    - pillow >=3.1
    - pytest
  commands:
    - pytest -v tests
    # Skip dfor windows (just needed for 64-bit) as there are some .pyc duplicates causing test failure.
    - python scripts/run_examples.py  # [not win]
    - constructor -V
  imports:
    - constructor

about:
  home: http://github.com/conda/constructor
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: create installer from conda packages
  description: |
    Constructor is a tool for constructing an installer for a collection of
    conda packages. It creates an Anaconda-like installer consisting of
    packages.
  doc_url: https://conda.io/projects/conda/en/latest/
  dev_url: https://github.com/conda/constructor

extra:
  recipe-maintainers:
    - jakirkham
    - jschueller
    - mbargull
    - msarahan
