{% set version = "1.7.0.dev9" %}

package:
  name: constructor
  version: {{ version }}

source:
  git_url: https://github.com/conda/constructor.git
  git_tag: cross_conda_interface

build:
  number: 0
  script: python setup.py install

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - conda
    - ruamel_yaml
    - pillow >=3.1  # [win]
    - nsis          # [win]

test:
  imports:
    - constructor

  commands:
    - constructor --help

about:
  home: http://github.com/conda/constructor
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: create installer from conda packages

extra:
  recipe-maintainers:
    - jakirkham
    - kalefranz
    - msarahan
    - mingwandroid
    - nehaljwani
