{% set version = "3.7.0" %}

package:
  name: constructor
  version: {{ version }}

source:
  - url: https://github.com/conda/constructor/archive/{{ version }}.tar.gz
    sha256: e84de1d7db3dbd394c03fa0e966bd293729307b9de0c8733ed7189f422a4b5b5
    patches:                        # [aarch64]
      - raspberry-pi-warning.patch  # [aarch64]

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - constructor = constructor.main:main
  skip: true  # [py<38]

requirements:
  build:
    - patch  # [aarch64]
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - conda >=4.6
    - python
    - ruamel.yaml >=0.11.14,<0.19
    - conda-standalone
    - pillow >=3.1     # [win or osx]
    - nsis >=3.08      # [win]
    # Even though this is not listed as a requirement,
    # building an installer will not work without it
    - jinja2
  run_constrained:     # [unix]
    - nsis >=3.08      # [unix]
test:
  source_files:
    - tests
    - scripts
    - examples
  requires:
    - pip
    - pytest
    - conda-libmamba-solver
  commands:
    - pip check
    - pytest -v tests -k "not examples"
    # Long running integration tests
    # - python scripts/run_examples.py  # [not win]
    - constructor -V
  imports:
    - constructor

about:
  home: https://github.com/conda/constructor
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: create installer from conda packages
  description: |
    Constructor is a tool for constructing an installer for a collection of
    conda packages. It creates an Anaconda-like installer consisting of
    packages.
  doc_url: https://conda.github.io/constructor
  dev_url: https://github.com/conda/constructor

extra:
  recipe-maintainers:
    - jakirkham
    - jschueller
    - mbargull
    - msarahan
