{% set version = "3.4.5" %}

package:
  name: constructor
  version: {{ version }}

source:
  - url: https://github.com/conda/constructor/archive/{{ version }}.tar.gz
    sha256: 425a7b6825a3dba21c21d9234ff1ceac8efea6ebc14e2b0e80d0880f502b3e01

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - constructor = constructor.main:main
  skip: true  # [py<37]

requirements:
  build:
    - patch  # [not win]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - conda >=4.6
    - python
    - ruamel.yaml >=0.11.14,<0.18
    - conda-standalone
    # pillow is used without any guards, so we need it for all architectures
    # https://github.com/conda/constructor/blob/3.4.4/constructor/imaging.py#L11
    - pillow >=3.1
    - nsis >=3.08      # [win]
    # Even though this is not listed as a requirement,
    # building an installer will not work without it
    - jinja2
  run_constrained:     # [unix]
    - nsis >=3.08      # [unix]
test:
  source_files:
    - tests
    - scripts
    - examples
  requires:
    - pip
    - pytest
    - conda-libmamba-solver
  commands:
    - pip check
    - pytest -v tests -k "not examples"
    # Long running integration tests
    # - python scripts/run_examples.py  # [not win]
    - constructor -V
  imports:
    - constructor

about:
  home: https://github.com/conda/constructor
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: create installer from conda packages
  description: |
    Constructor is a tool for constructing an installer for a collection of
    conda packages. It creates an Anaconda-like installer consisting of
    packages.
  doc_url: https://conda.github.io/constructor
  dev_url: https://github.com/conda/constructor

extra:
  recipe-maintainers:
    - jakirkham
    - jschueller
    - mbargull
    - msarahan
