{% set version = "3.0.0" %}
{% set sha256 = "d19643c60c8681d96877a27a16dd7b03959f8e2fa10dfc7c8ec5637c14bc693a" %}

package:
  name: constructor
  version: {{ version }}

source:
  - fn: constructor-{{ version }}.tar.gz
    url: https://github.com/conda/constructor/archive/{{ version }}.tar.gz
    sha256: {{ sha256 }}
    patches:
      # can be removed in 3.0.1
      - 0001-make-directory-arg-optional.patch

  - url: https://repo.anaconda.com/pkgs/misc/conda-execs/conda-latest-{{ SUBDIR }}.exe

build:
  number: 0
  script:
    - mkdir $PREFIX/standalone_conda  # [not win]
    - cp conda-latest-{{ SUBDIR }}.exe $PREFIX/standalone_conda/conda.exe  # [not win]
    - mkdir %PREFIX%\standalone_conda  # [win]
    - COPY conda-latest-{{ SUBDIR }}.exe %PREFIX%\standalone_conda\conda.exe  # [win]
    - pip install --no-deps -vv .
  entry_points:
    - constructor = constructor.main:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - conda >=4.6
    - ruamel_yaml
    - pillow >=3.1     # [win]
    - nsis >=3.01      # [win]

test:
  imports:
    - constructor
  commands:
    - constructor --test

about:
  home: http://github.com/conda/constructor
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: create installer from conda packages

extra:
  recipe-maintainers:
    - jakirkham
    - mbargull
    - msarahan
