travis:
  secure:
    BINSTAR_TOKEN: 3tHakRkiwk8c+cAUp+AnAEUy7lK1M1xypBk/qlyD+1oAykOQMQRbBYAj24z+W7pi2ghJBPWnvIzOhrpPeByal4RuQJn730I9fa7lDgtIHWMxdzugBfQrbMEidhM2PprmtqHh7qJVq04XCUb/ztvkw/S4Y0w4jVzTuKZmAdbNsMc7wKDcpxLLpSIzaGMAd6ZznU/OouOmP1z14yertK/m6qT5kiKHAAvmKmZDniFG7uToqZX54HoMD7ErHhq0Kx9y4bHmhqC7eH3bIC3N6/ojYBVpjegn34W8fSTBFq/Hv4viMJOGKXdxRM8wAGIqX1mlWO5DJ5XrP6hoGavElDHraQLWSW11najhzZlPou61cZfChRS2RGjCG8JoYaZgSIqofykf2WpdK0z/Nx2VKAB8WHEIw07iVolDicGYXlh5wDL+8NcpwT8BYE/ghlUE7rld6xFbVcb7cF/N5DYzT6l+jXwoVXH2EoVG8aEegwfVeDGGQqsYctdGtgWYu5XSDKuMhO+E9t9Qh7g3p3qqekA+/g0puG76+hdW5B+SnmjKujhHlGB5SqOqfX9wK/OsJpmtTk1XkscgrFmXggRyxP/7CE093+IU7VE8/Kyf6qXhHCr1Psp68BJdxwsznFC6sTzbp8MlRSNGFPm4WJ4aH2/zkn9fZGcit5dD2RtHRrSYLQI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
